
include("libs/global")
include("libs/get_waiting")
include("libs/get_players")
include("libs/get_overcrowded")
include("libs/get_time")
include("libs/get_stucked")
include("libs/get_finance")
include("libs/get_koyan")
include("libs/get_lines")
include("libs/get_halts")

//コマンド一覧．不要な機能があればコメントアウトしてください．
commands["待機"] <- get_waiting_cmd()
commands["wait"] <- get_waiting_cmd()
commands["プレイヤー"] <- get_players_cmd()
commands["player"] <- get_players_cmd()
commands["赤棒"] <- get_overcrowded_cmd()
commands["赤帽"] <- get_overcrowded_cmd()
commands["akabo"] <- get_overcrowded_cmd()
commands["時間"] <- get_time_cmd()
commands["time"] <- get_time_cmd()
commands["財務"] <- get_finances_cmd()
commands["finance"] <- get_finances_cmd()
commands["路線"] <- get_lines_cmd()
commands["停車駅"] <- get_halts_cmd()

//ここからネタ枠
commands["きつね"] <- get_koyan_cmd()
commands["kitsune"] <- get_koyan_cmd()
commands["ねこ"] <- get_nyan_cmd()
commands["neko"] <- get_nyan_cmd()
commands["えび"] <- get_ebi_cmd()
commands["ebi"] <- get_ebi_cmd()
commands["ﾃﾚｰ"] <- get_tere_cmd()
commands["うに"] <- get_uni_cmd()
commands["うにー"] <- get_uni_cmd()
commands["uni"] <- get_uni_cmd()
commands["阪急"] <- get_hankyu_cmd()
commands["うさぎ"] <- get_usagi_cmd()
commands["usagi"] <- get_usagi_cmd()

//モニタリング一覧．不要な機能があればコメントアウトしてください．
monitored.append(chk_overcrowded_cmd(8, 1.5, 5000)) //赤棒検知． 引数...(頻度,警報を出す倍率, 警報を出す下限)
monitored.append(chk_stucked_cmd(4, 0.8)) //デッドロック検知． 引数...(頻度,警報を出す割合)

